// 导入 Next.js 的 Metadata 类型，用于定义页面元数据
import type { Metadata } from "next";
// 从 Google 字体库导入 Geist 和 Geist_Mono 字体
import { Geist, Geist_Mono } from "next/font/google";
// 导入全局样式文件
import "./globals.css";

// 配置 Geist 无衬线字体，设置变量名和字符子集
const geistSans = Geist({ 
  variable: "--font-geist-sans", 
  subsets: ["latin"], 
}); 

// 配置 Geist 等宽字体，设置变量名和字符子集
const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono", 
  subsets: ["latin"], 
}); 

// 定义页面的元数据，包含标题和描述
export const metadata: Metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
}; 

// 定义根布局组件，接收子组件作为参数
export default function RootLayout({ 
  children, 
}: Readonly<{ 
  children: React.ReactNode; 
}>) { 
  return ( 
    // 设置 HTML 语言为英语
    <html lang="en"> 
      <body 
        // 应用配置好的字体变量和抗锯齿样式
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      > 
        {children} 
      </body> 
    </html> 
  ); 
}
